language: python
python:
- '3.7'
install:
- pip install -e .[dev]
script: python -m unittest -v; flake8 .
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: Ifbdinf+OaughGrbLCu7YzkCKcBzVvm4ljwYzz4HXYfx1hWjC2RcvXs0jg8U6t8lEGZ9YKpj8KkzEJO+HeDsCf7zw2ZUuOimkdb5xCbFzWoy13lsjKx4uqiny0A8fcym4hxOLJfNaJoVOm4qwsACAA97w/GHqJCU1Uz09cM7qWx/OF3TdOy6uFX/ITIyzA1jRWQ6SdEBaOc+bqLHsSQTuXvKYwWUYeVM4zqQuhzPfBw02lBP00wCISKoTREzidpE/oT9AkfVoTSDgknMIzX3LlhSysb3lXYhXQRzSBxGpMXOLhbvA6Miz/3zJykUfLwfRpHDI2isihMU6x6Ub+RsoejhunF985NZeHUBZRApsTosJIJUBYmUTSybWq1w5DpyRQ271BiTKWp4MCEBjjDhVYrLcqlomQ8aGt3G7chwnA9142n4WLv+GZZvS5ktKEejnOECvxlV6tmn0Aoz+bdzjtga98zKmv8+6rlWP8tpKzCqkfesG9uIUQN1JKJ+16XiNC5ZpdXYJcFANBfnvuTFDxP2cxH6H3gtAwp9wtIDwNVbaf9r30OEvS/V9E9iiVBrE9JSwyoQPeEctdOuNKzM1lYiYFw5psbN+MU7yG4VsurGvI3GdrOeVT/+wWLgbXzhsudl7E3PZ6okJNran1Hv2fEPtDG8uczdJpZGvLfyKdQ=
  on:
    branch: master
    
